In [27]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd

In [28]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [40]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [41]:
df['target'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [47]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop(['target'], axis = 'columns'), df.target, test_size=0.2)

In [50]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)
#lr.predict(x_test)

c:\users\91863\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


1.0

In [51]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

1.0

In [53]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9666666666666667

In [55]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [56]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [58]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

In [72]:
score_l = []
score_svm = []
score_rf = []
for train_index, test_index in folds.split(iris.data, iris.target):
    x_train, x_test, y_train, y_test = iris.data[train_index], iris.data[test_index], iris.target[train_index], iris.target[test_index]
    score_l.append(get_score(LogisticRegression(solver = 'liblinear', multi_class = 'ovr'), x_train, x_test, y_train, y_test))
    score_svm.append(get_score(SVC(gamma = 'auto'), x_train, x_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators = 40), x_train, x_test, y_train, y_test))


In [73]:
score_l

[0.96, 0.96, 0.94]

In [74]:
score_svm

[0.98, 0.98, 0.96]

In [75]:
score_rf

[0.98, 0.94, 0.94]

In [76]:
#cross validation for logistic regression
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

c:\users\91863\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [77]:
np.average(l_scores)

0.9733333333333334

In [79]:
#Decision Tree
dt_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
dt_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [80]:
np.average(dt_scores)

0.9666666666666668

In [81]:
#Support Vector Machine
svm_scores = cross_val_score(SVC(), iris.data, iris.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [82]:
np.average(svm_scores)

0.9666666666666666

In [83]:
#Random Forest
rf_scors = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
rf_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [84]:
np.average(rf_scores)

0.9666666666666668

###  We can observe here that Logistic Regression gives the best result