In [52]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [53]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.2)

In [54]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

c:\users\91863\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9638888888888889

In [55]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9833333333333333

In [56]:
rf = RandomForestClassifier(n_estimators = 40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9694444444444444

In [57]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [58]:
#Example of splitting data for k fold cross validation
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [59]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [60]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [62]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index],\
    digits.target[train_index], digits.target[test_index]
    
    scores_l.append(get_score(LogisticRegression(solver = 'liblinear', multi_class = 'ovr'), x_train, x_test, y_train, y_test))
    
    scores_svm.append(get_score(SVC(gamma = 'auto'), x_train, x_test, y_train, y_test))
    
    scores_rf.append(get_score(RandomForestClassifier(n_estimators = 40), x_train, x_test, y_train, y_test))

In [63]:
scores_l

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [64]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [65]:
scores_rf

[0.9348914858096828, 0.9365609348914858, 0.9232053422370617]

## cross_val_score fuction

In [66]:
from sklearn.model_selection import cross_val_score

### Logistic Regression performance using cross cross val
cross_val_score uses stratifield kfold by default

In [70]:

cross_val_score(LogisticRegression(solver = 'liblinear', multi_class = 'ovr'), digits.data, digits.target, cv = 3)

array([0.89482471, 0.95325543, 0.90984975])

In [71]:
#Support Vector Machine
cross_val_score(SVC(gamma = 'auto'), digits.data, digits.target, cv = 3)

array([0.38063439, 0.41068447, 0.51252087])

In [72]:
#Random Forest
cross_val_score(RandomForestClassifier(n_estimators = 40), digits.data, digits.target, cv = 3)

array([0.91652755, 0.94991653, 0.92320534])

## Parameter tunning using k fold cross validation

In [73]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators = 5), digits.data, digits.target, cv = 10)
np.average(scores1)

0.8686809435133457

In [75]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target, cv = 10)
np.average(scores2)

0.940996275605214

In [80]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators = 100), digits.data, digits.target, cv = 10)
np.average(scores3)

0.9504686530105524

Here we used cross_val_score to fine tune our random forest classifier and figured out that around 100 trees in random forest gives best result.